park_adjustments = {
    "TGS": {
        "Anaheim Angels": -0.94,
        "Arizona Diamondbacks": -0.8,
        "Atlanta Hammers": 1.92,
        "Baltimore Orioles": -2.38,
        "Boston Red Sox": 0.67,
        "Chicago Cubs": -0.82,
        "Chicago White Sox": 0.03,
        "Cincinnati Reds": -0.82,
        "Cleveland Guardians": 3.72,
        "Colorado Rockies": -6.06,
        "Detroit Tigers": 0.5,
        "Florida Marlins": 2.2,
        "Houston Astros": -1.66,
        "Kansas City Monarchs": -0.25,
        "Kansas City Royals": 0.52,
        "Los Angeles Dodgers": 3.45,
        "Milwaukee Brewers": 0.61,
        "Minnesota Twins": -0.25,
        "Montreal Expos": 1.09,
        "New York Mets": -6.06,
        "New York Yankees": -0.13,
        "Oakland Athletics": -2.38,
        "Philadelphia Phillies": 3.45,
        "Pittsburgh Pirates": 1.18,
        "San Diego Padres": 2.97,
        "San Francisco Giants": 3.45,
        "Seattle Mariners": -0.82,
        "St. Louis Cardinals": -6.06,
        "Tampa Bay Devil Rays": 0.51,
        "Texas Rangers": 3.72,
        "Toronto Blue Jays": -0.11,
        "Washington Nationals": -0.8,
    },
    "PBL": {
        "BAL": 0.0,
        "BOS": 0.0,
        "BRO": 0.0,
        "COL": 0.0,
        "DAL": 0.0,
        "LV": 0.0,
        "LA": 0.0,
        "MEM": 0.0,
        "MES": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "NO": 0.0,
        "OC": 0.0,
        "PHO": 0.0,
        "SCO": 0.0,
        "TUL": 0.0,
        "CHA": 0.0,
        "CLE": 0.0,
        "FRE": 0.0,
        "GLE": 0.0,
        "HON": 0.0,
        "IND": 0.0,
        "NY": 0.0,
        "NN": 0.0,
        "OMA": 0.0,
        "PHI": 0.0,
        "POR": 0.0,
        "REN": 0.0,
        "SAC": 0.0,
        "SA": 0.0,
        "SJ": 0.0,
        "SEA": 0.8,
    },
    "BZ": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.0,
    },
    "Dugout": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.8,
    },
    "BZ-Standard": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.0,
    },
    "BZ-Aging-Only": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.0,
    },
    "BZ-Dev-Focus": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.0,
    },
    "BZ-Dev-Test": {
        "ARI": 0.0,
        "ATL": 0.0,
        "BOS": 0.0,
        "CHC": 0.0,
        "CHW": 0.0,
        "CHN": 0.0,
        "CLE": 0.0,
        "COL": 0.0,
        "DET": 0.0,
        "HOU": 0.0,
        "KC": 0.0,
        "LAA": 0.0,
        "LAD": 0.0,
        "MIA": 0.0,
        "MIL": 0.0,
        "MIN": 0.0,
        "MON": 0.0,
        "NYM": 0.0,
        "NYA": 0.0,
        "OAK": 0.0,
        "PHI": 0.0,
        "PIT": 0.0,
        "SD": 0.0,
        "SEA": 0.0,
        "SF": 0.0,
        "STL": 0.0,
        "TBA": 0.0,
        "TEX": 0.0,
        "TOR": 0.0,
        "VAN": 0.0,
        "WAS": 0.0,
    },
}


def get_park_adjustments(league: str) -> dict[str, float]:
    """
    Get the park adjustments for the league

    Args:
    league: str: The league to get the park adjustments for

    Returns:
    dict[str, float]: The park adjustments for the league
    """

    return park_adjustments[league]
